### ISSUE TITLE
Visualization prediction vs. actual

### ISSUE THREAD

**Issue by pohlchri** [thuml/Time-Series-Library#192]
Thank you very much for the project! Regarding the visualization graph at the end of the tutorial.ipynb, I understand that every 20 steps a graph is plotted. For the 'M' multivariate setting for which input column is this graph actually plotted for instance in the ETTh1 dataset used? How can I change the column?

**Comment by GuoKaku** [comment]
Hi, when using 'M' mode, it's true that multi variables are predicted. Since we use visualization just for checking how the model behaves, in our code we only plotted one column of the input. See  function [visual](https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#234) in test part, and you'll find that we take out the last dim(-1) of both truth and prediction to plot. So if you'd like to change the column, simply change -1 to any dimension you want.

**Comment by pohlchri** [comment]
Thank you very much for your explanation!!
