### ISSUE TITLE
Problem in FFT_for_Period(...) in TimesNet.py

### ISSUE THREAD

**Issue by maheshyadav007** [thuml/Time-Series-Library#266]
Hi, 
Thanks for creating and maintaining this wonderful repo. I have a doubt in "FFT_for Period(...)" function, can you please comment on it?

1. In Line 17 of TimesNet.py `period = x.shape[1] // top_list`. Instead dividing by top_list which contain the indices, shouldn't we divide by the frequencies value. Here top_list contains the indices of the top k frequencies. 
2. Since we are giving the batched inputs to the above function. Won't there be lot of noise while calculating the top k frequencies. the batch may not even contain the necessary information to detect top k frequencies. 
3. Will TimesNet work if seq_len << period in Time series. For e.g. let's say, I am using seq_len = 100 for a dataset that has periodic nature after every 1440 data points. What will happen in this case?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your comments.
(1) It is notable that the i-th element in the `FFT` results represents the amplitude of frequency-i, which means that indices are frequency and the values are amplitudes of corresponding frequency.
(2) Actually, in our experiments, the top-k frequencies are quite stable. You can run the code for validation. 
(3) If seq_len << period, I believe that the first thing you need to do is to enlarge the input length. All the forecasting models will fail in this setting, since the input cannot provide enough information.

**Comment by zmx1012** [comment]
您好，frequency_list = abs(xf).mean(0).mean(-1)代码 运行到这 出现nvrtc: error: invalid value for --gpu-architecture (-arch)这个问题怎么解决啊
