### ISSUE TITLE
freq_map

### ISSUE THREAD

**Issue by LeqiGu** [thuml/Time-Series-Library#377]
![1712212720698](https://github.com/thuml/Time-Series-Library/assets/108117237/1b54b64e-d2bf-45f7-b851-89e795181250)
请问这个freq_map里面不同时间维度所映射的数字是如何确定的，他们有什么用？ 谢谢！

**Comment by cem-sirin** [comment]
I am not sure, since I am new to this repository. Though, I think based on the `freq` variable, you indicate how many dimensions you have for representing time. And you represent time with `x_mark`. So for example if you input `freq='h'` (which I interpret as hourly data), then your `x_mark` should have 4 columns, that corresponds to
- the month $\{0,\dots,11\}$
- the week $\{0,\dots,4\}$, or the day of the month $\{0,\dots,30\}$
- the day $\{0,\dots,6\}$
- the hour $\{0,\dots,23\}$

I hope that helps till you can get a more certain answer from the authors!

**Comment by wuhaixu2016** [comment]
Hi, thanks for the answer of @cem-sirin . It is correct.
