### ISSUE TITLE
关于autoformer的embedding方式

### ISSUE THREAD

**Issue by 534145232** [thuml/Time-Series-Library#385]
我想请问一下autoformer的输入编码为什么用的是DataEmbedding_wo_pos，为什么不需要位置信息呢。同样的FEDformer依旧是用的原来的embedding函数

**Comment by wuhaixu2016** [comment]
您好，请见Autoformer官方的README.md（https://github.com/thuml/Autoformer）
Get Started下面有一个Special-designed implementation

Without the position embedding: Since the series-wise connection will inherently keep the sequential information, Autoformer does not need the position embedding, which is different from Transformers.
