### ISSUE TITLE
Train Loss is higher than Validation and Test Loss

### ISSUE THREAD

**Issue by well0203** [thuml/Time-Series-Library#397]
Hi, thank you for your work!

I am trying Informer architecture and wanted to ask whether it is normal that my Train Loss is higher than Validation and Test Losses. I tried to split my data on 60%/20%/20%; 70%/10%/20% and other configurations. I am trying multivariate (M) setting with default parameters and seq_len=96, label_len=48, pred_len=24. But I suppose it can be the case in other models too. Thanks for help.

**Comment by wuhaixu2016** [comment]
Hi, many thanks for coming up with this great point.

According to my experience, this situation may be because of the temporal domain shift of time series, which means the future variation can be simpler than past observations.

I recommend you try the Non-stationary Transformer, which utilizes instance normalization to enhance the stability of the time series. This design can mitigate this abnormal case.

**Comment by well0203** [comment]
> Hi, many thanks for coming up with this great point.
> 
> According to my experience, this situation may be because of the temporal domain shift of time series, which means the future variation can be simpler than past observations.
> 
> I recommend you try the Non-stationary Transformer, which utilizes instance normalization to enhance the stability of the time series. This design can mitigate this abnormal case.

Thank you, I thought of 2 cases: first is that you responded. The second is because you report training metrics averaged "during training" per epoch, while validation and test metrics are measured after the model is trained on that epoch, therefore it could lead to such results.
