### ISSUE TITLE
short term forecasting error

### ISSUE THREAD

**Issue by Shangshi-Chen** [thuml/Time-Series-Library#499]
Dear author,
 I downloaded the m4 dataset from short_term_forecast folder in your google drive and place it under /dataset folder. But when I run bash ./scripts/short_term_forecast/TimesNet_M4.sh, it pops out a ValueError: ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (414,) + inhomogeneous part. Wish youc could help to explain more about this.

**Comment by wuhaixu2016** [comment]
Sorry, we did not reproduce this issue. Can you provide more details, such as a snapshot of your training log?

**Comment by Shangshi-Chen** [comment]
Sure. First picture shows that m4 dataset is put under dataset folder and is intact. Second picture is my command in terminal. Third and forth pictures are the popped out error. By the way, I didn't follow your requirement.txt but I don't think that matter is relevant.[
![1](https://github.com/user-attachments/assets/bd0777ca-83a1-46cf-9043-dfd02cea6788)
![2](https://github.com/user-attachments/assets/3653ac16-6249-454e-84be-966de6c955ab)
![3](https://github.com/user-attachments/assets/a05066fb-a058-44b3-a81a-3e28e7e314e8)
![4](https://github.com/user-attachments/assets/e9ddb303-0ab0-4fda-9cd8-eb14f9977420)
](url)

**Comment by Shangshi-Chen** [comment]
And by the way, I have little suggestions for you. It's really complicated to train your model on customed dataset and produce forecast. It will be perfect if you could give an intergrated function or api that takes certain format of dataframe as input (specific format can be explained in document) and train and produce forecast like scikit-learn. You can refer to neuralforecast who has included lots of your sota models but with a super easy usage. This will make your work applicable to a wider audience.

**Comment by oskarjor** [comment]
I had the same error. When downgrading to Python 3.8 and using the same package versions as in requirements.txt, the issue was resolved.

**Comment by wuhaixu2016** [comment]
Thanks for the detailed information and the answer from @oskarjor . 

Still, we cannot reproduce this in the Linux environment. However, one of my labmates reproduced this issue in the Windows environment. Thus, this may be caused by the operating system.

To be more concrete, this problem is caused by https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L341-L343 . If your environment or Numpy version does not support varied length array, the program will throw this error. I think changing the Numpy version can be helpful.

**Comment by yoom618** [comment]
I think it is an error that occurs when having numpy higher than v1.24. 
(Since I used the latest version of all libraries in the requirements, my numpy version was 2.1.3)

For me, just adding , `dtype="object"` argument inside the `np.array()` in line 341-343 solved the problem. [(reference)](https://stackoverflow.com/questions/67183501/setting-an-array-element-with-a-sequence-requested-array-has-an-inhomogeneous-sh))

**Comment by yoom618** [comment]
I think it is an error that occurs when having numpy higher than v1.23. 
(Since I used the latest version of all libraries in the requirements, my numpy version was 2.1.3)

For me, adding `, dtype=np.ndarray` argument inside the `np.array()` in line 341-343 seemed to solve the problem. [(reference)](https://stackoverflow.com/questions/67183501/setting-an-array-element-with-a-sequence-requested-array-has-an-inhomogeneous-sh)
