### ISSUE TITLE
Are there any multimodal neural networks for time-series?

### ISSUE THREAD

**Issue by tueboesen** [thuml/Time-Series-Library#571]
Let me start by saying I really like you guys work, and I think the code is very nice and easy to use!
Unfortunately I have not found a way to use any of these neural networks for the following problem, hopefully someone can give me some insight or ideas about whether this is possible.

I am looking for a neural network for time series that can handle non-time series input.

Specifically a neural network where I can give it a single main time serie (and perhaps additional auxiliary time series), and some properties about this particular time series. With the goal of forecasting the  main time serie.

As an example, suppose I have individual household energy consumptions, but my measurements are not all from the same time period. Some houses I only have for 2023, while others start in 2024 ect. To go with each of these energy consumptions time series, I might have additional information about the consumer household, like the size of the house or the number of people living in the house, or just a unique house_id.
I would like to train my neural network on this kind of time series, utilizing these additional parameters in some sort of embedding such that the neural network is able to generate accurate predictions for any of these household when given its specific embedding.

So something that looks like: 
forecasting=model(input_time_serie, auxiliary_time_series,  additional_properties) 
where input_time_serie is a single time serie vector of length n, auxiliary_time_series are optional time series of length n (could be outside temperature, time of the week, ect.), and additional_properties is a vector of length m containing property parameters that is somehow embedded inside the neural network and allows the neural network to distinguish between two different households. 

Such a neural network could hopefully also be used in zero-shot predictions, where we do not yet have any actual energy consumption for the household, but only have the embedding data.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your appreciation of TSLib and for asking an interesting question.

I think our recent paper can perfectly solve the task that you described: https://arxiv.org/pdf/2410.03806v1 . In this paper, we refer to the "some properties about this particular time series" as metadata, which is encoded by large language models. The proposed method is named MetaTST, which can do a great job in handling multi-dataset join training.

Regrettably, we cannot open source now since the paper is still under review. According to the convention of our lab, we will publicize the code after acceptance.

**Comment by tueboesen** [comment]
This sounds exactly like what I am looking for, thank you very much for the prompt reply and good luck with the review process!
