### ISSUE TITLE
Getting NaN Train and Vali Loss with classification models

### ISSUE THREAD

**Issue by kikoyuan** [thuml/Time-Series-Library#575]
Hi guys,
Thanks for hard work, this project is amazing.
However, I've been accountered with some issues when I run for Classification models (TimesNet, iTransformer...)
I'm using a handcraft dataset in .ts format. There are 13 features and 1 label.
As you can see from the figure, **_Train Loss_** and **_Vali Loss_** have always been **_NaN_**.
![issue](https://github.com/user-attachments/assets/d0471286-4c9c-4b8a-a17f-130f7fc01565)
I've tried to use another dataset, handcrafted same way, and get regular results.
In other posts, I've read about that this may due to **_normalization_** or **_d_ff._** .
Could you be more specific about these two reasons, like when we need to change that and how do these methods/parameters affect all?

**Comment by wuhaixu2016** [comment]
Sorry for the delayed response. I have not come across similar problems. I think you can print the model output before calculating the cross_entropy and see if there are already some problems after the model output.

If it is possible, you can also send your data to my email: wuhx23@mails.tsinghua.edu.cn, I will check where the problem is.
