### ISSUE TITLE
Examples of settings for large models.

### ISSUE THREAD

**Issue by pskucherov** [thuml/Time-Series-Library#583]
I have a large dataset and the default settings make predictions quite well.
But I have a feeling that it can be even better. In addition, the GPU RAM is not fully utilized and there is a reserve of 20 GB for increasing the model.

I tried changing different parameters so that the model occupies the entire GPU RAM. But the predictions usually became worse than with the default settings or just a straight horizontal line on the resulting graph.

Perhaps the settings have dependencies that I do not see and do not follow. Or they should not be touched at all, because it will not get better.

Advise how you would increase the settings in my situation?
Do you have examples of presets for large models that I could research?

**Comment by wuhaixu2016** [comment]
Hi, thanks for coming up with this interesting question.

Generally speaking, it depends on the type of your time series data. If your data contains a large number of variates, then increasing `--d_model` can be helpful. Otherwise, over-parameterization may cause the overfitting problem. In addition, enlarging the input length `--seq_len` is also usually helpful. 

Furthermore, I think training a model on large datasets can be quite empirical. You may need some tricks like data balancing or data normalization.
