### ISSUE TITLE
TimesNet Training Speed

### ISSUE THREAD

**Issue by junwoopark92** [thuml/Time-Series-Library#87]
Thank you for your excellent job. 

I have some questions for TimesNet.

When training TimesNet on traffic and electricity, it takes almost an hour for one epoch, whereas other Transformer-based models take around 10 minutes. Can you explain why TimesNet is so slow?

and why does the TimesNet set batch size as 1 in evaluation?  Maybe due to the batch-wise reduction in the FFT process of TimesNet?

Thank you in advance.

**Comment by wuhaixu2016** [comment]
(1) About the Traffic and ECL dataset
The training speed gets slow due to the large d_model. This is because of that these two datasets contains extremely large variates (ECL: 321; Traffic: 872). Thus, I think a large d_model is more reasonable. If you decrease the d_model into 128, the model performance will also acceptable.
If you want to speed up, you can adopt the channel independent setting that is treating the multivariate time series as multiple univariate time series. But this will also cause large GPU memory.

(2) About the evaluation batch size, you can find a complete discussion here (in Chinese): https://github.com/thuml/Time-Series-Library/issues/62. Here are the key points:
- Batch size as 1 can avoid the future leaky.
- In real-world application, a serving system will only receive one sample at each time. Thus, set batch size as 1 will not affect the real-world usage.
